server:
  port: 8081

spring:
  application:
    name: demo-gateway
  cloud:
    # nacos的配置(这个nacos.host,请换成自己的nacos地址)
    nacos:
      discovery:
        server-addr: nacos.host:8848
    # gateway的配置
    gateway:
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: false
      routes:
      # 路由组名
      - id: service
        # lb负载均衡访问, 后面是模块的application.name
        uri: lb://demo-service
        # 匹配规则, 最好api-模块名的规范匹配
        predicates:
        - Path=/api-service/**
        # 截取访问路径的前缀
#        routes:
#          filters:
#            -StripPrefix=1

